name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    services:
      mongodb:
        image: mongo:6.0
        env: 
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: admin
        ports:
          - 27017:27017
        options: --quiet --bind_ip 0.0.0.0

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build the app
      run: npm run build --if-present

    - name: Wait for MongoDB to start
      run: |
        for i in {1..30}; do
          if nc -z mongodb 27017; then
            echo "MongoDB is ready";
            break;
          fi
          echo "Waiting for MongoDB...";
          sleep 1;
        done
        if ! nc -z mongodb 27017; then
          echo "MongoDB failed to start";
          exit 1;
        fi

    - name: Run tests
      env:
        SECRET: HAHA
        DB_URI: "mongodb://mongodb:27017"  # Update MongoDB URI to use the service name
        PORT: 80
      run: npm test
